apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-with-dapr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: pythonapp
        imagePullPolicy: Never

      - name: dapr
        image: daprio/daprd:edge
        command: ["./daprd"]
        args:
          - "-app-id"
          - "pythonapp"
          - "-placement-host-address"
          - "placement:50006"
          - "-components-path"
          - "/components"
        volumeMounts:
          - mountPath: "/components"
            name: components-volume

      volumes:
        - name: components-volume
          hostPath:
            path: ${COMPONENTS_PATH}
